# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('Mother_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
